version: '2.4'

services:
  jenkins:
    build: jenkins_controller
    container_name: jenkins
    ports:
      - "8880:8080"
      - "50000:50000"
    restart: always
    volumes:
      - ./jenkins_controller/jenkins.yaml:/usr/share/jenkins/ref/jenkins.yaml
      - ./jenkins_agent/jenkins.yaml:/usr/share/jenkins/ref/jenkins.yaml
  SonarQube:
    image: sonarqube:10.2.1-community
    container_name: sonaqrube
    depends_on:
      - jenkins
    ports:
      - "9000:9000"
    restart: always

  